baseURL = 'https://sixtyfouroftheclock.github.io/'
languageCode = 'en'
title = "sixtyfour o'clock"
theme = 'chimera'
enableRobotsTXT = true

[sitemap]
  filename = "sitemap.xml"
  changefreq = "monthly"
  priority = 0.5
